// src/app/(dashboard)/modules/[code]/RequirementAiHelp.tsx
"use client";

import { useState, useTransition } from "react";
import Link from "next/link";
import type { Route } from "next";
import { Sparkles, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { askRequirementHelpAction } from "./ai-actions";

export interface RequirementAiHelpProps {
  frameworkCode: string;
  requirementCode: string;
  requirementTitle: string;
  requirementDescription?: string;
  currentStatus?:
    | "NOT_STARTED"
    | "IN_PROGRESS"
    | "COMPLIANT"
    | "GAP"
    | "NOT_APPLICABLE";
  practiceState?: string;
  specialty?:
    | "PRIMARY_CARE"
    | "SPECIALTY"
    | "DENTAL"
    | "BEHAVIORAL"
    | "ALLIED"
    | "OTHER"
    | null;
}

export function RequirementAiHelp(props: RequirementAiHelpProps) {
  const [isPending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);
  const [open, setOpen] = useState(false);
  const [answer, setAnswer] = useState<string | null>(null);
  const [firstStep, setFirstStep] = useState<{
    label: string;
    href: string;
  } | null>(null);

  const handleAsk = () => {
    setError(null);
    setOpen(true);
    if (answer) return; // already loaded; just toggle open
    startTransition(async () => {
      const res = await askRequirementHelpAction({
        frameworkCode: props.frameworkCode,
        requirementCode: props.requirementCode,
        requirementTitle: props.requirementTitle,
        requirementDescription: props.requirementDescription,
        currentStatus: props.currentStatus,
        practiceState: props.practiceState,
        specialty: props.specialty ?? undefined,
      });
      if (res.ok) {
        setAnswer(res.answer);
        setFirstStep(res.firstStep ?? null);
      } else {
        setError(res.error);
      }
    });
  };

  if (!open) {
    return (
      <Button
        type="button"
        size="sm"
        variant="ghost"
        className="h-7 px-2 text-[11px] text-muted-foreground"
        onClick={handleAsk}
        disabled={isPending}
      >
        <Sparkles className="mr-1 h-3 w-3" aria-hidden="true" />
        AI help
      </Button>
    );
  }

  return (
    <div className="mt-2 rounded-md border bg-muted/30 p-3 text-[11px]">
      <div className="mb-1.5 flex items-center justify-between gap-2">
        <p className="flex items-center gap-1 font-semibold text-foreground">
          <Sparkles className="h-3 w-3" aria-hidden="true" />
          AI suggestion
        </p>
        <button
          type="button"
          onClick={() => setOpen(false)}
          className="text-muted-foreground hover:text-foreground"
          aria-label="Close AI suggestion"
        >
          <X className="h-3 w-3" aria-hidden="true" />
        </button>
      </div>
      {isPending && !answer && (
        <p className="text-muted-foreground">Thinking…</p>
      )}
      {error && (
        <p className="text-[color:var(--gw-color-risk)]">{error}</p>
      )}
      {answer && (
        <div className="space-y-2">
          <p className="whitespace-pre-line text-foreground">{answer}</p>
          {firstStep && (
            <Button asChild size="sm" variant="outline" className="text-[10px]">
              <Link href={firstStep.href as Route}>{firstStep.label} →</Link>
            </Button>
          )}
          <p className="text-[9px] text-muted-foreground">
            Generated by Claude. Verify against the current regulation
            text + your state-specific rules.
          </p>
        </div>
      )}
    </div>
  );
}
