// src/app/(dashboard)/audit/activity/ActivityExplain.tsx
//
// Inline AI "explain this" affordance for a single activity-log row.
// Renders a tiny "✦ Explain" button. Clicking expands a small
// inline panel with a 2-3 sentence plain-English explanation, an
// optional related-citation badge, and an optional next-action CTA.

"use client";

import { useState, useTransition } from "react";
import Link from "next/link";
import type { Route } from "next";
import { Sparkles, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { askActivityExplainAction } from "./ai-actions";

export interface ActivityExplainProps {
  eventType: string;
  summary: string;
  payloadPreview?: string;
  actorFirstName?: string;
  practiceState?: string;
}

export function ActivityExplain(props: ActivityExplainProps) {
  const [isPending, startTransition] = useTransition();
  const [open, setOpen] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [explanation, setExplanation] = useState<string | null>(null);
  const [relatedCitation, setRelatedCitation] = useState<string | null>(null);
  const [nextAction, setNextAction] = useState<{
    label: string;
    href: string;
  } | null>(null);

  const handleAsk = () => {
    setError(null);
    setOpen(true);
    if (explanation) return; // already loaded; just toggle open
    startTransition(async () => {
      const res = await askActivityExplainAction({
        eventType: props.eventType,
        summary: props.summary,
        payloadPreview: props.payloadPreview,
        actorFirstName: props.actorFirstName,
        practiceState: props.practiceState,
      });
      if (res.ok) {
        setExplanation(res.explanation);
        setRelatedCitation(res.relatedCitation ?? null);
        setNextAction(res.nextAction ?? null);
      } else {
        setError(res.error);
      }
    });
  };

  if (!open) {
    return (
      <Button
        type="button"
        size="sm"
        variant="ghost"
        className="h-6 px-1.5 text-[10px] text-muted-foreground"
        onClick={handleAsk}
        disabled={isPending}
      >
        <Sparkles className="mr-0.5 h-2.5 w-2.5" aria-hidden="true" />
        Explain
      </Button>
    );
  }

  return (
    <div className="mt-1.5 rounded-md border bg-muted/30 p-2.5 text-[11px]">
      <div className="mb-1 flex items-center justify-between gap-2">
        <p className="flex items-center gap-1 font-semibold text-foreground">
          <Sparkles className="h-3 w-3" aria-hidden="true" />
          AI explanation
        </p>
        <button
          type="button"
          onClick={() => setOpen(false)}
          className="text-muted-foreground hover:text-foreground"
          aria-label="Close explanation"
        >
          <X className="h-3 w-3" aria-hidden="true" />
        </button>
      </div>
      {isPending && !explanation && (
        <p className="text-muted-foreground">Thinking…</p>
      )}
      {error && (
        <p className="text-[color:var(--gw-color-risk)]">{error}</p>
      )}
      {explanation && (
        <div className="space-y-1.5">
          <p className="whitespace-pre-line text-foreground">{explanation}</p>
          {relatedCitation && (
            <Badge variant="outline" className="text-[9px]">
              {relatedCitation}
            </Badge>
          )}
          {nextAction && (
            <Button asChild size="sm" variant="outline" className="text-[10px]">
              <Link href={nextAction.href as Route}>{nextAction.label} →</Link>
            </Button>
          )}
          <p className="text-[9px] text-muted-foreground">
            Generated by Claude. Verify against the current regulation
            text + your state-specific rules.
          </p>
        </div>
      )}
    </div>
  );
}
